# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88f8743c7c3d4afb15091f0379e49da836f67a8b2eb34127984693bd411cc31055e9dcf9e4dea04a0715ecef198c578914914e4990146699190b09fc9b31699b

test:
  secret_key_base: f7945e5bd06db100927192dc59305b9b7e34baa3a0257bcbeb6cd236a1ee5e6a13b31f70fa7e25ffca406080a08dc179481cb7c9092110cdc2f09bb3e51d980a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
